name: Internal test suite

permissions:
  contents: read

on:
  pull_request:
  push:

jobs:
    test-apache-container:
        name: Test (${{ matrix.configuration }}) on database ${{ matrix.database-image }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                database-image: ["mariadb:10.4", "mysql:5.7", "mariadb:latest", "mysql:latest"]
                configuration: ["default", "one-host", "fs-import-export", "different-apache-port"]

        steps:
            - uses: actions/checkout@v3
            - name: Build images
              working-directory: ./testing/
              run: docker-compose -f ./docker-compose/docker-compose.testing-${{ matrix.configuration }}.yml build
            - name: Run ${{ matrix.configuration }} tests
              working-directory: ./testing/
              run: docker-compose -f ./docker-compose/docker-compose.testing-${{ matrix.configuration }}.yml up --build --abort-on-container-exit --exit-code-from=sut
              env:
                DB: ${{ matrix.database-image }}
